site_name: pudu

site_url: https://pudu-py.github.io/pudu

repo_url: https://github.com/pudu-py/pudu

theme:
    palette:
        scheme: preference
    name: material
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - search.highlight
        # - navigation.expand
        # - navigation.tabs
    custom_dir: "docs"

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
          include_source: True
        #   execute: True
          
markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

# extra:
#     analytics:
#         provider: google
#         property: UA-XXXXXXXXX-X

nav:
    - Home: docs/index.rst
    - Installation: docs/quickstart.rst
    - Usage: docs/
    - Contributing: docs/contributions.rst
    - Report Issues: https://github.com/pudu-py/pudu/issues
    - API Reference:
          - pudu module: docs/pudu.rst
