name: docs
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3.1.0
            - uses: actions/setup-python@v4.3.0
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install --user --no-cache-dir Cython
                  pip install --user -r requirements.txt
                  pip install --user -r requirements_dev.txt
            - name: PUDU-TEST
              run: |
                  python -m unittest discover tests/
            - run: python -m pip install --upgrade pip
            - run: pip install mkdocs-material mkdocstrings mkdocstrings-python-legacy mkdocs-git-revision-date-plugin mkdocs-jupyter ipykernel
            - run: mkdocs gh-deploy --force
